# data
data:
  eval_data: '' # Optional Fill
  shuffle: true
  train_data: '' # Fill

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

# -------- Training mode --------
# Set to true to fine-tune every weight of the model. When this is enabled
# make sure that **lora.enable** remains **false** and **save_adapters** is
# also **false** (we will save the full model instead).
full_finetuning: true

# LoRA specific arguments – keep them disabled when doing a full fine-tune.
lora:
  enable: false
  rank: 128       # Ignored when enable is false
  scaling: 2.     # Ignored when enable is false
  ft_embed: false # Ignored when enable is false

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 100
batch_size: 16
max_steps: 2000
gradient_checkpointing: true
optim:
  lr: 2e-6
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
do_eval: false
do_ckpt: true
ckpt_freq: 100

# When doing full finetuning **save_adapters** must be set to *false* so that
# the complete model checkpoint is stored.
save_adapters: false

run_dir: ""  # Fill

# This part is optional and can be kept commented out
# wandb:
#   project: "" # your wandb project name
#   run_name: "" # your wandb run name
#   key: "" # your wandb api key
#   offline: False
